Algoritmo "Matrices / Arrays"
  Var
    l, c: inteiro
    array: vetor[1..5, 1..3] de inteiro

Inicio
  Para l <- 1 ate 5 passo 1 faca
    Para c <- 1 ate 3 passo 1 faca
      Escreva("Position: [", l, c, " ] :")
      Leia(array[l, c])
    
    FimPara
  
  FimPara
  
  Escreval
  
  Para l <- 1 ate 5 passo 1 faca
    Para c <- 1 ate 3 passo 1 faca
      Escreva(array[l, c])
    
    FimPara
    
    Escreval()

  FimPara



FimAlgoritmo