Algoritmo "Soma e média simples"

Var
 NumberA, NumberB : real
 Sum:real
 Media:real
Inicio
 Escreval("Digite dois valores reais e direi-lhe a soma e média entre eles")
 Escreva()
 leia(NumberA, NumberB)

 Sum <- NumberA + NumberB
 Escreval("A soma é dada por:", NumberA, " + ", NumberB, " = ", Sum)
 Escreval("A média aritmética simples entre esses valores equivale a", (NumberA + NumberB)/2)


Fimalgoritmo